###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    redis:
      image: redis:alpine
      container_name: rainblog-redis

    postgres:
      image: postgres:9.6-alpine
      ports: 
        - "5433:5432"
      container_name: rainblog-postgres
      working_dir: /application
      volumes:
        - .:/application
        - ./var/lib/postgresql/data:/var/lib/postgresql/data
      environment:
        - PGDATA=/var/lib/postgresql/data
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=qw88@11
        - POSTGRES_DB=faraway-blog

    elasticsearch:
      image: elasticsearch:5.4-alpine
      container_name: rainblog-elasticsearch

    webserver:
      image: nginx:alpine
      container_name: rainblog-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./etc/nginx/conf.d:/etc/nginx/conf.d
      ports:
       - "80:80"
       - "8081:81"       
       - "8082:82"       

    php-fpm:
      build: phpdocker/php-fpm
      container_name: rainblog-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini

    console:
      build: phpdocker/console
      container_name: rainblog-console 
      volumes: 
        - .:/application
      tty: true
     
    node:
      build: phpdocker/node
      container_name: rainblog-node
      volumes:
        - .:/application
      tty: true
